Repository yumdari/Home_AIoT_System, pull requests merged in 2022-07, with the labels that each got.

#20 Feature/socket
  README.md
  Tablet/lib/_userA.dart
  Tablet/lib/_userB.dart
  Tablet/lib/main.dart
  Tablet/lib/userA.dart
  Tablet/lib/userB.dart
  Tablet/lib/weather.dart
  Tablet/pubspec.lock
  Tablet/pubspec.yaml
  Tablet/test/widget_test.dart
Labels: 📱 Application

#21 feat: object detection 보완 및 기능 추가
  README.md
  image_contour/img.cpp
  image_contour/video.cpp
Labels: Jetson Nano

#25 feat: object detection 기능 보완 및 추가
  README.md
  image_contour/img.cpp
  image_contour/video_Trackbar.cpp
Labels: 📷Image Proccessing

#26 fix: object detection 수정
  image_contour/video_Trackbar.cpp
Labels: 🛠hotfix, 📷Image Proccessing

#16 feat : ESP32 Client
  README.md
  proclient.ino
Labels: ⚙️Actuator

#17 Feature/raspberry pi
  chat_clnt.c
  chat_clnt2.c
  chat_server.c
  socket_server.c
Labels: 🛢 DB

#33 OpenCV on Jetson Nano with Cmake
  README.md
  image_processing/CMakeLists.txt
  image_processing/Makefile
  image_processing/haarcascade_frontalface_alt.xml
  image_processing/src/main.cpp
Labels: 📷Image Proccessing, priority : critical🔥🔥🔥
