Repository yumdari/Home_AIoT_System, pull requests merged in 2022-09, with the labels that each got.

#37 feat : Push notification for face & box detection and finger print error
  Mobile/android/app/build.gradle
  Mobile/android/app/src/main/res/drawable-hdpi/ic_stat_linked_camera.png
  Mobile/android/app/src/main/res/drawable-mdpi/ic_stat_linked_camera.png
  Mobile/android/app/src/main/res/drawable-xhdpi/ic_stat_linked_camera.png
  Mobile/android/app/src/main/res/drawable-xxhdpi/ic_stat_linked_camera.png
  Mobile/android/app/src/main/res/drawable-xxxhdpi/ic_stat_linked_camera.png
  Mobile/lib/CameraViewer.dart
  Mobile/lib/DataPage.dart
  Mobile/lib/HomeIoT.dart
  Mobile/lib/Time.dart
  Mobile/lib/main.dart
  Mobile/lib/notification.dart
  Mobile/pubspec.lock
  Mobile/pubspec.yaml
  README.md
Labels: 📱 APP, priority : 보통

#38 feat : Add present time on CameraViewer page (yyyy년MM월dd일 hh:mm:ss)
  Mobile/lib/CameraViewer.dart
  Mobile/lib/HomeIoT.dart
  Mobile/lib/Time.dart
  Mobile/lib/main.dart
  Mobile/pubspec.lock
  Mobile/pubspec.yaml
  README.md
Labels: 📱 APP, priority : 보통

#39 feat : Add button to screenshot video widget and save the image file into gallery
  Mobile/android/app/src/main/AndroidManifest.xml
  Mobile/lib/CameraViewer.dart
  Mobile/lib/main.dart
  Mobile/pubspec.lock
  Mobile/pubspec.yaml
  README.md
Labels: 📱 APP, priority : 중요

#41 Feature/python cv
  README.md
  streaming_server/haarcascade_frontalface_alt.xml
  streaming_server/haarcascade_frontalface_default.xml
  streaming_server/server.py
Labels: 📷Image Proccessing, priority : critical🔥🔥🔥

#42 feat : MCU 최종
  MCU/ESP32.ino
  MCU/ProMini.ino
  MCU/server.c
  README.md
  client/chat_clnt.c
  client/chat_clnt2.c
  db/SelectDB
  db/SelectDB.c
  db/SelectDB.o
  proclient.ino
  server/chat_server.c
Labels: 🛢 DB, ⚙️Actuator, 📡Sensor, priority : 중요

#43 Fix : Create a pointer on gauge of LED
  Mobile/lib/CameraViewer.dart
  Mobile/lib/HomeIoT.dart
  Mobile/lib/main.dart
  README.md
Labels: 🛠hotfix, 📱 APP, priority : 중요
